/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "accel.h"
#include "i2c_lcd.h"
#include "i2c.h"
#include "spi.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	char str[32];
	char str1[32];
	LIS_Data val;
	SystemInit();
	Lcd_Init();
	LIS_Init(); //initialize accel
	while(1) {
		if(LIS_IsDataAvail()) // check if new data avail
		{
			val = LIS_GetData(); // get the new data
			// print value
			sprintf(str, "X=%d, Y=%d, Z=%d \n", val.x, val.y);
			Lcd_Puts(LCD_LINE1, str);
			sprintf(str1, "Z=%d \n", val.z);
			Lcd_Puts(LCD_LINE2, str1);
		}
		DelayMs(1000);
	}
	return 0;
}
